# Importing Numpy

In [5]:
import numpy as np
np.__version__


'1.18.1'

# Function No: 1 - Creating 1D Array

In [13]:
ar=np.array(["Ali","Zeeshan","Imtiaz"])
ar

array(['Ali', 'Zeeshan', 'Imtiaz'], dtype='<U7')

# Function No: 2--Creating 2D Array

In [19]:
arr=np.array([["Waqar","Suhail","Imtiaz"],["Shakhrukh","Ameer","Alice"]])
arr

array([['Waqar', 'Suhail', 'Imtiaz'],
       ['Shakhrukh', 'Ameer', 'Alice']], dtype='<U9')

# Function No: 3 - Creating 3D Array

In [78]:
arr1=np.array([[[11,22,33,44],[55,66,77,88],[99,101,110,120]]])
arr1

array([[[ 11,  22,  33,  44],
        [ 55,  66,  77,  88],
        [ 99, 101, 110, 120]]])

# Function No: 4 - arange

In [32]:
a=np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

# Function No: 5 - Shape

In [75]:
list=[[1,2,3,4],[5,6,7,8]]
l=np.shape(list)
l


(2, 4)

# Function No: 6 - Re-Shape

In [93]:
l2=np.arange(50).reshape(5,10)
l2


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Function No:7  - arange function gap between values

In [89]:
a = np.arange(2,40,5)
a

array([ 2,  7, 12, 17, 22, 27, 32, 37])

# Function No: 8 - array of 10 with divided value

In [100]:
z=np.linspace(10,100,10)
z

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Function No: 9 - Number of Dimensions

In [105]:
a=np.array([[(1,2,3),(4,5,6),(7,8,9)]])
a.ndim

3

# Function No: 10 - Size

In [108]:
a=np.array([(1,2,3,4,5,6,7)])
a.size

7

# Function No: 11 - ItemSize

In [112]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a.itemsize

4


# Function No: 12 - Dtype

In [114]:
a=np.array([(1,2,3)])
a.dtype

dtype('int32')

# Function No: 13 - Data

In [115]:
a=np.arange(10)
a.data



# Function No: 14 - Zeros

In [118]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

# Function No: 15 - Ones

In [119]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

# Function No: 16 - Empty

In [120]:
a=np.empty(5)
a

array([1., 1., 1., 1., 1.])

# Function No: 17 - Random

In [121]:
a=np.random.randint(4, size=10)
a

array([1, 0, 2, 0, 0, 2, 3, 0, 2, 0])

# Function No:18 - Slicing

In [125]:
a=np.array([(1,2,3,4),(3,4,5,6)])
a[0:,2]

array([3, 5])

# Function No: 19 - Max

In [129]:
a=np.array([1,2,3,4])
a.max()

4

# Function No: 20 - Min

In [130]:
a=np.array([1,2,3,4])
a.min()

1

# Function No: 21 - Sort

In [137]:
b = np.array([[4, 3, 2, 4], [3,4,2,6]])
b.sort()
b

array([[2, 3, 4, 4],
       [2, 3, 4, 6]])

# Function No: 22 - Addition 

In [138]:
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,4),(5,6,5)])
x+y

array([[ 2,  4,  7],
       [ 8, 10, 10]])

# Function No 23: - Division

In [139]:
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,4),(5,6,5)])
x/y

array([[1.        , 1.        , 0.75      ],
       [0.6       , 0.66666667, 1.        ]])

# Function No 24: - Standard Deviation 

In [142]:
x=np.array([(1,2,3),(3,4,5)])
np.std(x)

1.2909944487358056

# Function No 25: - Square Root

In [143]:
x=np.array([(1,2,3),(3,4,5)])
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798]])

# Function No 26: - Full

In [148]:
x = np.full((4,3),4)
x

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

# Function No: 27: - Vertical Stacking

In [152]:
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,3),(3,4,5)])
np.vstack((x,y))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 3],
       [3, 4, 5]])

# Function No: 28: - Horizontal Stacking

In [153]:
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,3),(3,4,5)])
np.hstack((x,y))

array([[1, 2, 3, 1, 2, 3],
       [3, 4, 5, 3, 4, 5]])

# Function No: 29: - Mean

In [154]:
x=np.array([(1,2,3),(3,4,5)])
np.mean(x)

3.0

# Function No: 30: - Uniform

In [156]:
a = np.random.uniform(1,50, 20)
a

array([43.83194236, 12.18727119, 29.08712788, 45.31257787, 11.54096361,
       10.19118419, 23.89444991, 38.44146807, 49.52218163,  7.55650284,
        8.75017215, 34.27060019, 12.15723448, 29.83072495, 43.90741658,
       34.75024006, 29.11548408,  5.01627528,  6.04623577, 25.53609562])

# Function No. 31: - Concatenate

In [157]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
x = np.concatenate((a1, a2))
x

array([1, 2, 3, 4, 5, 6])

# Function No. 32: - Ravel

In [159]:
x=np.array([(1,2,3),(2,3,4)])
x.ravel()

array([1, 2, 3, 2, 3, 4])

# Function No. 33: - Iteration

In [160]:
a = np.array([[5, 6, 2], [1, 4, 8]])

for x in a:
  print(x)

[5 6 2]
[1 4 8]


# Function No. 34: - Power

In [161]:
a = np.array([1,2,4,7,3])
np.power(a,3)

array([  1,   8,  64, 343,  27], dtype=int32)

# Function No. 35: - Seed

In [163]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

# Function No. 36: - Setdiff - 1D

In [164]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([5,6,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4, 7])

# Function No: 37: - Filtering

In [165]:
a = np.array([2,5,6,2,8,9,10,11])
b = np.array([5,7,9,2,2,3,5,11])

np.where(a == b)

(array([3, 7], dtype=int64),)

# Function No: 38: - Picking Even Numbers

In [168]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(b % 2 == 0)

(array([0, 2, 4, 6, 8], dtype=int64),)

# Function No: 39: - Picking Odd Numbers

In [169]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(b % 2 == 1)

(array([1, 3, 5, 7, 9], dtype=int64),)

# Function No: 40: - Reverse Array

In [171]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b[:0:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

# Function No: 41 - Replace Values in Array

In [172]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.put(b, [0, 3], [15, 40])
b

array([15,  1,  2, 40,  4,  5,  6,  7,  8,  9])

# Function No: 42 - Get Values by index from array

In [173]:
b = np.array([3,7,4,8,5,4,4,3])
np.take(b, [2,4,5])

array([4, 5, 4])

# Function No: 43 - Return Index of Non - Zero Element

In [174]:
b = np.array([3,7,4,8,5,4,4,3])
np.take(b, [2,4,5])

array([4, 5, 4])

# Function No: 44 - Cumulative Sum

In [176]:
b = np.array([1,6,3,0,8,0,2,0,4,5])
b.cumsum()

array([ 1,  7, 10, 10, 18, 18, 20, 20, 24, 29], dtype=int32)

# Function No: 45 - Repeat

In [177]:
c=np.repeat(4,5)
c

array([4, 4, 4, 4, 4])

# Function No. 46: - Count Non Zero

In [178]:
b = np.array([1,6,3,0,8,0,2,0,4,5])
np.count_nonzero(b)

7

# Function No. 47: - Element wise Modulus Operator

In [179]:
d = np.array([1,6,3,0,8,0,2,0,4,5])
np.mod(d, 2)==0

array([False,  True, False,  True,  True,  True,  True,  True,  True,
       False])

# Function No. 48: -Apprend items to end of array

In [180]:
b = np.array([1,6,3,0,8,0,2,0,4,5])
np.append(b, [2,3,4])

array([1, 6, 3, 0, 8, 0, 2, 0, 4, 5, 2, 3, 4])

# Function No. 49:- Return Unique No.

In [181]:
d = np.array([1,1,3,99,0,3,0,2,0,5,4,2])
np.unique(d)

array([ 0,  1,  2,  3,  4,  5, 99])

# Function No. 50: - Place

In [182]:
arr = np.arange(8).reshape(4, 2)
np.place(arr, arr>5, [44, 55])
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [44, 55]])